name: Deploy Front Production

on:
  push:
    branches: ['main', 'feat/cicd']

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v2
      
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false      
          
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
          
      - name: Install dependencies
        run: |
          pnpm install
          pnpm build
        env:
          PUBLIC_GA: ${{ env.PUBLIC_GA }}  
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "ap-northeast-2"

      - name: Deploy
        run: |
          aws s3 rm s3://${{ secrets.AWS_BUCKET_FRONT }} --recursive
          aws s3 sync ./dist s3://${{ secrets.AWS_BUCKET_FRONT }}

      - name: Invalidate CloudFront (cosanam.com)
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: E1PRZOLT3TSKMF
          PATHS: "/*"
          AWS_REGION: "ap-northeast-2"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          